### PR TITLE
Git Ignore update and target color

### PR DESCRIPTION
**Pull request by milansky**
Updated git ignore file to exclude PyCharm files and folders

Changed red color of the target system to be more readable with black text in the background

### CODE REVIEW

**Comment by milansky** [comment]
Things changed:

Color modified for target systems to be more readable
Updated file names to match color
Updated ReadMe file to match image filenames and display accordingly
Updated gitignore file for Pycharm files

**Comment by NoFoolLikeOne** [comment]
Sorry, I'm terrible seeing these getting notifications. 

Your changes look greaty but we now have some conflicts, 

Would you be able to resove them and then I'll merge it

Thanks you!

**Comment by milansky** [comment]
No worries, I'll take a look and resolve the conflicts.

**Comment by milansky** [comment]
@NoFoolLikeOne Conflicts resolved, please take a look and let me know if you want me to change anything :)

**Pull request merged**
